### PR TITLE
fix lack of py files in linux

### PR DESCRIPTION
**Pull request by hmaarrfk**
Closes https://github.com/conda-forge/pydantic-core-feedstock/issues/79
Closes #80 
Closes #81 
Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by hmaarrfk** [comment]
@conda-forge-admin please rerender

**Comment by erykoff** [comment]
Still failing...

**Comment by hmaarrfk** [comment]
> Still failing...

I'm not sure what this is supposed to mean. 

I know it is failing. for some reason i managed to get it working once locally with what I thought was due to `--no-build-isolation` but I guess i was wrong. 

I marked as draft to communicate that it isn't perfect.

I'm skipping the large build matrix to save CIs while I troubleshoot.

**Comment by erykoff** [comment]
Yeah, I thought the `--no-build-isolation` was the thing as well, and then I checked back and noticed that it didn't work.  I see you're trying the old version to see if it's something with pydantic or something with one of the build tools that changed.  Not fun!

**Comment by hmaarrfk** [comment]
The crazy thing, i've reverted all these packages:
image


Maybe i have to revert rust too???
image

**Comment by erykoff** [comment]
Did this ever work? Is the problem that pydantic feedstock needs no build isolation and that’s installing these extra files? (Just speculating based on crazy evidence so far)

**Comment by hmaarrfk** [comment]
See current theory 

https://github.com/conda-forge/pydantic-core-feedstock/pull/81#issuecomment-1868130915

**Comment by xhochy** [comment]
I didn't see an option in `maturin` to ignore the `gitignore`, so we need to live with this workaround for now :(

**Comment by xhochy** [comment]
This means that all maturin based projects are currently broken 😱

**Comment by xhochy** [comment]
Posted https://github.com/conda-forge/conda-smithy/pull/1818 as a workaround

**Comment by samuelcolvin** [comment]
Merging this has closed all associated issues, but I'm unclear if the problem is actually fixed?

**Comment by davidhewitt** [comment]
Thanks @hmaarrfk @xhochy 🙏

**Pull request merged**
